AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MinhaChave:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Selecione o par de chaves
  Envs:
    Description: Selecione um ambiente
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Mappings:
  MeuMapaRegiao:
    us-east-1:
      IDREGIAO: ami-0022f774911c1d690
    us-west-1:
      IDREGIAO: ami-02541b8af977f6cdd
  MeuMapaAmbientes:
    dev:
      instanciaTipo: t2.micro
    prod:
      instanciaTipo: t2.small

Resources:
  MinhaInstanciaVM:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MeuMapaRegiao
        - !Ref "AWS::Region"
        - IDREGIAO
      InstanceType: !FindInMap
        - MeuMapaAmbientes
        - !Ref Envs
        - instanciaTipo
      KeyName: !Ref MinhaChave