AWSTemplateFormatVersion: 2010-09-09

Description: CFN Init Demo

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources: 
  MeuGrupoSeguro:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Meu grupo de seguranca
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'          
          ToPort: '8080'
          CidrIp: 0.0.0.0/0

  MinhaVM:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Deploy de aplicacao tomcat
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              java-1.8.0-openjdk.x86_64: []
              java-1.8.0-openjdk-devel: []
              tomcat8: []
          groups:
            grupoum: {}
            grupodois:
              gid: "501"
          users:
            usuum:
              groups:
                - grupoum
                - grupodois
              uid: "501"
              homeDir: "/tmp"
          sources:
            /tmp: https://cnf-init-11-05.s3.amazonaws.com/cnf/demo1.zip
          files:
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=7
              mode: "000400"
              owner: "root"
              group: "root"
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.MinhaVM.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cnf-init -v --stack ${AWS::StackName} --resource MinhaVM --region ${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
          commands:
            test1:
              command: "chmod 755 demo.war"
              cwd: "/tmp"
            test2:
              command: "sudo yum -y erase java-1.7.0-openjdk.x86_64"
              cwd: "~"
            test3:
              command: "rm -rf demo"
              cwd: "/var/lib/tomcat8/webapps"
            test4:
              command: "cp demo.war /var/lib/tomcat8/webapps"
              cwd: "/tmp"
          services:
            sysvinit:
              tomcat8:
                enabled: "true"
                ensureRunning: "true"
    Properties:
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MeuGrupoSeguro
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash xe
            # Get latest cnf package
            yum update -y aws-cfn-bootstrap
            /opt/aws/bin/cnf-init -s ${AWS::StackId} -r MinhaVM --region ${AWS::Region} || error_exit 'Falhou ao rodar cnf-init'