AWSTemplateFormatVersion: 2010-09-09
Description: KeyName Parameter demo

Parameters:
  MyKeyName:
    Description: Selecione uma chave da lista
    Type: AWS::EC2::KeyPair::KeyName

Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default        
        - !Ref SSHSecurityGroup 
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0