AWSTemplateFormatVersion: 2010-09-09
Description: Parametrizacao de zona disponivel

Parameters:
  MyKeyName:
    Description: Selecione uma chave da lista
    Type: AWS::EC2::KeyPair::KeyName
  MinhasZonasDisponiveis:
    Description: Selecione a zona
    Type: String
    Default: us-east-1b
    AllowedValues:
      - us-east-1b
      - sa-east-1a
      - us-east-2a
  MinhasInstanciasDisponiveis:
    Description: Selecione um tipo de instancia do SSM
    Type: AWS::SSM::Parameter::Value<String>

    
Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0022f774911c1d690
      InstanceType: !Ref MinhasInstanciasDisponiveis
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default        
        - !Ref SSHSecurityGroup 
      AvailabilityZone: !Ref MinhasZonasDisponiveis
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: my new SSH security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0