AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Envs:
    Description: Selecione um ambiente
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - QA

Mappings:
  MeuMapaRegiao:
    us-east-1:
      IDREGIAO: ami-0022f774911c1d690
    us-west-1:
      IDREGIAO: ami-02541b8af977f6cdd
  MeuMapaAmbientes:
    dev:
      instanciaTipo: t2.micro
    prod:
      instanciaTipo: t2.small
    QA:
      instanciaTipo: t2.medium

Conditions:
  CriarElasticIPParaProd: !Equals [!Ref Envs, prod]
  CriarGrupoSeguroDev: !Not [{Condition: CriarGrupoSeguroProd}]
  CriarGrupoSeguroProd: !Equals [!Ref Envs, prod]
  SeRegiaoUsarChaveValor: !And [!Or [!Equals [!Ref "AWS::Region", us-east-1], !Equals [!Ref "AWS::Region", us-west-2]], !Equals [!Ref Envs, dev]]

Resources:
  MinhaInstanciaVM:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MeuMapaRegiao
        - !Ref "AWS::Region"
        - IDREGIAO
      InstanceType: !FindInMap
        - MeuMapaAmbientes
        - !Ref Envs
        - instanciaTipo
      KeyName: !If [SeRegiaoUsarChaveValor, cfn-chave-2, cfn-chave-1]
      SecurityGroups: !If [CriarGrupoSeguroDev, [!Ref MeuGrupoDeSegurancaDev], [!Ref MeuGrupoDeSegurancaProd]]
  MeuEIPProd:
    Type: AWS::EC2::EIP
    Condition: CriarElasticIPParaProd
    Properties:
      InstanceId: !Ref MinhaInstanciaVM
  MeuGrupoDeSegurancaDev:
    Type: AWS::EC2::SecurityGroup
    Condition: CriarGrupoSeguroDev
    Properties:
      GroupDescription: Seguranca de DEV
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
  MeuGrupoDeSegurancaProd:
    Type: AWS::EC2::SecurityGroup
    Condition: CriarGrupoSeguroProd
    Properties:
      GroupDescription: Seguranca de PROD
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0