AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Envs:
    Description: Selecione um ambiente
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: Deve ser desenvolvimento ou producao
  MinhasInstanciasDisponiveis:
    Description: Selecione um tipo de instancia
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  MinhasChaves:
    Description: Selecione uma chave da lista
    Type: AWS::EC2::KeyPair::KeyName
  MinhasZonasDisponiveis:
    Description: Selecione a zona
    Type: String
    Default: us-east-1b
    AllowedValues:
      - us-east-1b
      - sa-east-1a
      - us-east-2a

Conditions:
  CriarEIPProd: !Equals [!Ref Envs, prod]

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Configuracao Intancia EC2"
        Parameters:
          - MinhasInstanciasDisponiveis
          - MinhasChaves
          - MinhasZonasDisponiveis
      - Label:
          default: "Configuracao de ambiente"
        Parameters:
          - Envs
    ParameterLabels:
      Envs:
        default: "Qual ambiente deseja criar a instancia?"
      MinhasChaves:
        default: "Escolha uma chave e que nao podera ser alterada."

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0022f774911c1d690
      InstanceType: !Ref MinhasInstanciasDisponiveis
      KeyName: !Ref MinhasChaves
      AvailabilityZone: !Ref MinhasZonasDisponiveis

  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: CriarEIPProd
    Properties:
      InstanceId: !Ref MyVMInstance
